use Bookworm
go

SET IDENTITY_INSERT [dbo].[Editoriales] ON 

INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (1, N'Acantilado')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (2, N'Alfaguara')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (3, N'Amazonia Editorial')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (4, N'Anfora')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (5, N'Avon')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (6, N'Createspace')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (7, N'Crown Publishers')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (8, N'Debolsillo')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (9, N'del Nuevo Extremo')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (10, N'Dolmen')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (11, N'Doubleday Books')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (12, N'Ediciones B')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (13, N'Ediciones NACE')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (14, N'El Ateneo')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (15, N'Feedbooks')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (16, N'Grijalbo')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (17, N'Harper')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (18, N'Indiana University')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (19, N'John Wiley & Sons')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (20, N'Mestas Ediciones')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (21, N'NAL')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (22, N'Planeta')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (23, N'Plaza y Janés')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (24, N'Pomaire')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (25, N'Raincoast Books')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (26, N'RBA')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (27, N'Scribner')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (28, N'Sergio Adrián Martin')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (29, N'Severed Press')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (30, N'Signet Classics')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (31, N'Sudamericana')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (32, N'The University of Chicago')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (33, N'Umbriel')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (34, N'University Press of Mississippi')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (35, N'Vergara Editor')
INSERT [dbo].[Editoriales] ([ID], [Nombre]) VALUES (36, N'Wiley-Blackwell')
SET IDENTITY_INSERT [dbo].[Editoriales] OFF